routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('pets', 'PetController');

app/Pet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Pet extends Model
{
    protected $fillable = [
    'nombre',
    'edad',
    'especie',
    'clasificacion',
    'peso',
    'pais_origen',
  ];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PetController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Pet;
use DB;
class PetController extends Controller
{
    //

    public function index()
    {
        //$pets = Pet::all();
        $pets = DB::table('pets')->get();

        return view('pets.index', compact('pets'));
    }


    public function store(Request $request)
    { 
      $request->validate([
        'nombre'=>'required|max:50',
        'edad'=> 'required|integer|max:3',
        'especie' => 'required|max:30',
        'clasificacion' => 'max:20',
        'peso' => 'required|integer|max:100',
        'pais_origen' => 'required|max:30'
      ],[
        'nombre.required'=>'El nombre es requerido',
        'nombre.max'=>'El nombre no debe tener mas de 50 caracteres',
        'edad.required'=>'la edad es requerida',
        'edad.max'=>'La edad es expresada en año, no debe tener más de 3 dígitos',
        'edad.integer' => 'La edad debe ser un número',
        'especie.required'=>'La especie es requerida',
        'especie.max'=>'La especie no debe tener más de 30 dígitos',
        'clasificacion.max'=>'La clasificacionno debe tener más de 20 dígitos',
        'peso.required'=>'El peso es requerido',
        'peso.max'=>'El peso no debe tener mas de 3 caracteres',
        'peso.integer' => 'El peso debe ser un número',
        'pais_origen.required'=>'El pais de origen es requerido',
        'pais_origen.max'=>'El pais de origen no debe tener mas de 30 caracteres',
      ]);
      


/*
      $pet = new Pet([
        'nombre' => $request->get('nombre'),
        'edad'=> $request->get('edad'),
        'especie'=> $request->get('especie'),
        'clasificacion'=> $request->get('result'),
        'peso'=> $request->get('peso'),
        'pais_origen'=> $request->get('pais_origen'),
      ]);
      $pet->save();
*/

      DB::table('pets')->insert(
     [  'nombre' => $request->get('nombre'),
        'edad'=> $request->get('edad'),
        'especie'=> $request->get('especie'),
        'clasificacion'=> $request->get('result'),
        'peso'=> $request->get('peso'),
        'pais_origen'=> $request->get('pais_origen'), ]
      );


      return redirect('/pets')->with('success', 'La mascota se ha agregado correctamente');
    }


     public function edit($id)
    {
        //$pet = Pet::find($id);
       $pet = DB::table('pets')->where('id',$id)->first();

        return view('pets.edit', compact('pet'));
    }


    public function update(Request $request, $id)
    {
      $request->validate([
        'nombre'=>'required|max:50',
        'edad'=> 'required|integer|max:100',
        'especie' => 'required|max:30',
        'clasificacion' => 'max:20',
        'peso' => 'required|integer|max:100',
        'pais_origen' => 'required|max:30'
      ],[
        'nombre.required'=>'El nombre es requerido',
        'nombre.max'=>'El nombre no debe tener mas de 50 caracteres',
        'edad.required'=>'la edad es requerida',
        'edad.max'=>'La edad es expresada en año, no debe tener más de 3 dígitos',
        'edad.integer' => 'La edad debe ser un número',
        'especie.required'=>'La especie es requerida',
        'especie.max'=>'La especie no debe tener más de 30 dígitos',
        'clasificacion.max'=>'La clasificacionno debe tener más de 20 dígitos',
        'peso.required'=>'El peso es requerido',
        'peso.max'=>'El peso no debe tener mas de 3 caracteres',
        'peso.integer' => 'El peso debe ser un número',
        'pais_origen.required'=>'El pais_origen es requerido',
        'pais_origen.max'=>'El pais_origen no debe tener mas de 30 caracteres',
      ]);
      
      
      DB::table('pets')->where('id',$id)->update(
     [  'nombre' => $request->get('nombre'),
        'edad'=> $request->get('edad'),
        'especie'=> $request->get('especie'),
        'clasificacion'=> $request->get('result'),
        'peso'=> $request->get('peso'),
        'pais_origen'=> $request->get('pais_origen'), ]
      );

      
      /*
      $pet = new Pet([
        'nombre' => $request->get('nombre'),
        'edad'=> $request->get('edad'),
        'especie'=> $request->get('especie'),
        'clasificacion'=> $request->get('result'),
        'peso'=> $request->get('peso'),
        'pais_origen'=> $request->get('pais_origen'),
      ]);
      $pet->save();
*/




      return redirect('/pets')->with('success', 'La mascota se ha editado correctamente');
    }


public function destroy($id)
{
/*
     $pet = Pet::find($id);
     $pet->delete();

*/
     
      DB::table('pets')->where('id',$id)->delete();
     
     return redirect('/pets')->with('success', 'Stock has been deleted Successfully');
}
public function create(){
    return view('pets.create');
}

}

resources/views/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
  <title>Pets</title>
  <link href="{{ asset('css/app.css') }}" rel="stylesheet" type="text/css" />
</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{{ route('pets.index')}}">Pets</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{{ route('pets.index')}}">Pet list</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{ route('pets.create')}}">Add pet</a>
      </li>
      
    </ul>
  </div>
</nav>

  <div class="container">
    @yield('content')
  </div>
  <script src="{{ asset('js/app.js') }}" type="text/js"></script>
</body>


<!-- Footer -->
<footer style="padding-top: 35%;"class="page-footer font-small blue">

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="#">IVneo Software Developmnet</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

</html>

resources/views/pets/create.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Añadir mascota
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('pets.store') }}">
          <div class="form-group">
              @csrf
              <label for="nombre">Nombre:</label>
              <input type="text" class="form-control" name="nombre" value="{{old('nombre')}}" />
          </div>
          <div class="form-group">
              <label for="edad">Edad:</label>
              <input type="text" class="form-control" name="edad" value="{{old('edad')}}" />
          </div>
          <div class="form-group">
              <label for="especie">Especie:</label>
              <input type="text" class="form-control" name="especie" value="{{old('especie')}}" />
          </div>
          
          <div class="form-group">
              <label for="clasificacion">Clasificacion</label>
              <br>
            <input type="radio" name="result" value="Salvaje" checked> Salvaje
            <input type="radio" name="result" value="Domestico"> Domestico
          <br><br>

      
          <div class="form-group">
              <label for="peso">Peso:</label>
              <input type="text" class="form-control" name="peso" value="{{old('peso')}}" />
          </div>

          <div class="form-group">
              <label for="pais_origen">Pais origen:</label>
              <input type="text" class="form-control" name="pais_origen" value="{{old('pais_origen')}}" />
          </div>
          <button type="submit" class="btn btn-primary">Agregar</button>
      </form>
  </div>
</div>
@endsection

resources/views/pets/edit.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('pets.update', $pet->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
              @csrf
              <label for="nombre">Nombre:</label>
              <input type="text" class="form-control" name="nombre" value="{{ $pet->nombre}}" />
          </div>
          <div class="form-group">
              <label for="edad">Edad:</label>
              <input type="text" class="form-control" name="edad"  value="{{ $pet->edad}}"/>
          </div>
          <div class="form-group">
              <label for="especie">Especie:</label>
              <input type="text" class="form-control" name="especie"  value="{{ $pet->especie}}"/>
          </div>
          
          <div class="form-group">
              <label for="clasificacion">Clasificacion</label>
              <br>
              @if($pet->clasificacion == 'salvaje')
            <input type="radio" name="result" value="Salvaje" checked > Salvaje
            <input type="radio" name="result" value="Domestico"> Domestico
            @else
            <input type="radio" name="result" value="Salvaje"  > Salvaje
            <input type="radio" name="result" value="Domestico" checked> Domestico
            @endif
            
          <br><br>

      
          <div class="form-group">
              <label for="peso">Peso:</label>
              <input type="text" class="form-control" name="peso"  value="{{ $pet->peso}}"/>
          </div>

          <div class="form-group">
              <label for="pais_origen">Pais origen:</label>
              <input type="text" class="form-control" name="pais_origen"  value="{{ $pet->pais_origen}}"/>
          </div>
          <button type="submit" class="btn btn-primary">Agregar</button>
      </form>
  </div>
</div>
@endsection

resources/views/pets/index.blade.php
@extends('layout')

@section('content')
<style>
  .uper {
    margin-top: 39px;
  }
  #b{
    margin-right: -10px;
  }
  #d{
    margin-right: -20px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div id="c"class="alert alert-success">
       <button id="cerrar" type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      {{ session()->get('success') }}  
    </div><br />

    <script>
      var button = document.querySelector('#cerrar');
     button.addEventListener('click', function(){
        document.querySelector('#c').style.display = 'none';
     });
    </script>




  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nombre</td>
          <td>Edad</td>
          <td>Especie</td>
          <td>Clasificación</td>
          <td>Peso</td>
          <td>Pais de origen</td>
          <td colspan="2">Acción</td>
        </tr>
    </thead>
    <tbody>
        @foreach($pets as $pet)
        <tr>
            <td>{{$pet->id}}</td>
            <td>{{$pet->nombre}}</td>
            <td>{{$pet->edad}}</td>
            <td>{{$pet->especie}}</td>
            <td>{{$pet->clasificacion}}</td>
            <td>{{$pet->peso}}</td>
            <td>{{$pet->pais_origen}}</td>
            <td><a id="b" href="{{ route('pets.edit',$pet->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('pets.destroy', $pet->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button  id="d"class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
            
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
  
@endsection